[workspace]
members = ["benchmarks", "cache2", "examples", "tests-integration", "xtask"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/scopedb/cache2"
rust-version = "1.98"

[workspace.dependencies]
# Workspace crates
cache2 = { path = "cache2", version = "0.2.1" }

# Crates.io dependencies
crc-fast = { version = "1.10.0", default-features = false, features = ["std"] }
io-uring = { version = "0.7.14" }
libc = { version = "0.2.189" }
log = { version = "0.4.31", features = ["kv"] }
logforth = { version = "0.30.1", default-features = false, features = ["bridge-log", "filter-rustlog", "layout-json"] }
mea = { version = "0.6.7" }
tokio = { version = "1.53.1", features = ["rt", "sync", "time"] }
twox-hash = { version = "2.1.4", default-features = false, features = ["std", "xxhash3_64"] }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
