[package]
name = "cache2-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
cache2 = { path = "../cache2", features = ["fuzzing"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "persistent_decoders"
path = "fuzz_targets/persistent_decoders.rs"
test = false
doc = false
bench = false

[workspace]
